name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: MaoenD
          outputs: |
            dist/github-contribution-grid-snake.svg
          palette: "github-dark"
          color_snake: "#bf00ff"
          color_dots: "#161b22,#0e4429,#006d32,#26a641,#39d353"
          background: "#0d1117"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
